name: Momentum Discord Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install requests pandas

      - name: Run alert
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python discord_alert.py
